codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
    after_n_builds: 2
coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%
comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
flags:
  slog:
    carryforward: true
    paths:
      - "driver/slog"
  zap:
    carryforward: true
    paths:
      - "driver/zap"