name: Go
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Test slog
        working-directory: ./driver/slog
        run: |
          go mod tidy
          go test -v -coverprofile=coverage.out ./...

      - name: Test zap
        working-directory: ./driver/zap
        run: |
          go mod tidy
          go test -v -coverprofile=coverage.out ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./driver/slog/coverage.out
          flags: unittests | slog | logger-driver
          fail_ci_if_error: true
          verbose: true

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./driver/zap/coverage.out
          flags: unittests | zap | logger-driver
          fail_ci_if_error: true
          verbose: true