name: Go
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Change dir
        run: cd driver/slog

      - name: Go mod tidy
        run: go mod tidy

      - name: Test slog
        run: go test -v -coverprofile=coverage.out ./...

      - name: Change dir
        run: cd ../zap

      - name: Test zap
        run: go test -v -coverprofile=coverage.out ./...

      - name: Change dir
        run: cd ../../

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./driver/slog/coverage.out,./driver/zap/coverage.out
          flags: unittests
          fail_ci_if_error: true
          verbose: true
